---
root: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'prettier'

parser: babel-eslint

env:
  browser: true
  node: true
  jest: true

rules:
  no-console: 0
  import/extensions: 0
  import/prefer-default-export: 0
  new-cap:
    - error
    - properties: false
